version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: tests and coverage
          command: npm run test-coverage
      - store_artifacts:
          path: coverage